version: '3.9'
services:
  web-project:
    build:
      context: .
    ports:
     - "8000:8000"
    volumes:
      - .:/website
    environment:
      - DB_HOST=database
      - DB_NAME=shop-internet
      - DB_USER=${USER}
      - DB_PASS=${PASSWORD}
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
  
  database:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_DB=shop-internet
      - POSTGRES_USER=${USER}   
      - POSTGRES_PASSWORD=${PASSWORD}


# version: "3.9"

# services:
#   db: 
#     image: postgres
#     volumes: 
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=shop-internet
#       - POSTGRES_USER=${USER}
#       - POSTGRES_PASSWORD=${PASSWORD}

#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#       - ./data/db:/var/lib/postgresql/dat
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db