version: '3.9'
services:
  web-project:
    build:
      context: .
    ports:
     - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DB_HOST=database
      - DB_NAME=shop-internet
      - DB_USER=${USER}
      - DB_PASS=${PASSWORD}
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      - redis
  
  database:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_DB=shop-internet
      - POSTGRES_USER=${USER}   
      - POSTGRES_PASSWORD=${PASSWORD}
  
  redis:
    image: redis:7.0.5-alpine
    hostname: redis