version: '3.9'
services:
  web-project:
    build:
      context: .
    ports:
     - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DB_HOST=database
      - DB_NAME=django
      - DB_USER=${USER}
      - DB_PASS=${PASSWORD}
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      - redis

  
  database:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=${USER}   
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ./dump_file.sql:/docker-entrypoint-initdb.d/dump_file.sql
  
  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker-1:
    build:
      context: .
    volumes:
      - .:/code
    command: >
      sh -c "celery -A website.celery worker --loglevel=info"
    depends_on:
      - redis
      - database

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A website.celery flower
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"