# Generated by Django 4.2.9 on 2024-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
