# Generated by Django 5.1 on 2024-10-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
    ]
